### ISSUE TITLE
Needs MIT license + contributor guidelines

### ISSUE THREAD

**Issue by lasomethingsomething** [zalando/cats.match#1]
Hi -- yeah, and the license needs to be included in the README doc as well, at the bottom, with the text. 

Do you have any "help wanted" ideas or plans that you could offer in the README, to get contributors started?

**Comment by danpersa** [comment]
I added the license to the README. There are no plans to get more contributions, as the library is already doing everything it is supposed to do.

**Comment by lasomethingsomething** [comment]
OK. All you have to do now is just update your license file with the MIT text (it's still Apache 2.0) and "la fin" :)

**Comment by danpersa** [comment]
done
