### ISSUE TITLE
Add support for Clojurescript

### ISSUE THREAD

**Issue by danpersa** [zalando/cats.match#2]

**Comment by ggeoffrey** [comment]
According to the changelog at `1.0.0 - 2016-12-16`, ClojureScript support is complete. Can this be closed or are there some missing features ?

**Comment by lasomethingsomething** [comment]
Thanks for asking and for being interested in our work, @ggeoffrey. Hey @danpersa, WDYT?

**Comment by ggeoffrey** [comment]
I'm using it on both clojure & clojurescript right now and it seems to be ok. But I prefer to ask before shipping things to prod :)

**Comment by danpersa** [comment]
@ggeoffrey,thanks for asking. It can be closed.
